export default {
    namespaced: true,
    state: {
        navigation:[
            {title:"按钮",to:"/Button"},
            {title:"图标",to:"/Icon"},
            {title:"文字链接",to:"/Link"},
            {title:"单选框",to:"/Radio"},
            {title:"多选框",to:"/Checkbox"},
            {title:"选择器",to:"/Select"},
            {title:"连级选择器",to:"/Cascader"},
            {title:"开关",to:"/Switch"},
            {title:"滑块",to:"/Slider"},
            {title:"时间选择器",to:"/TimePicker"},
            {title:"日期选择器",to:"/DatePicker"},
            {title:"时间日期选择器",to:"/DateTimePicker"},
            {title:"文件上传",to:"/Upload"},
            {title:"评分",to:"/Rate"},
            {title:"颜色选择器",to:"/ColorPicker"},
            {title:"穿梭框",to:"/Transfer"},
            {title:"表单",to:"/Form"},
            {title:"表格",to:"/Table"},
            {title:"标签",to:"/Tag"},
            {title:"进度条",to:"/Progress"},
            {title:"树形",to:"/Tree"},
            {title:"分页",to:"/Pagination"},
            {title:"头像",to:"/Avatar"},
            {title:"空状态",to:"/Empty"},
            {title:"警告",to:"/Alert"},
            {title:"加载",to:"/Loading"},
            {title:"消息提示",to:"/Message"},
            {title:"弹窗",to:"/MessageBox"},
            {title:"通知",to:"/Notifiation"},
            {title:"菜单导航",to:"/NavMenu"},
            {title:"面包屑",to:"/Breadcrumb"},
            {title:"下拉菜单",to:"/Dropdown"},
            {title:"步骤条",to:"/Steps"},
            {title:"对话框",to:"/Dialog"},
            {title:"文字提示",to:"/Tooltip"},
            {title:"卡片",to:"/Card"},
            {title:"走马灯",to:"/Carousel"},
            {title:"日历",to:"/Calendar"},
            {title:"图片",to:"/Image"},
            {title:"走马灯",to:"/Carousel"},
            {title:"回到顶部",to:"/BackTop"},
            {title:"抽屉",to:"/Drawer"},
        ]
    },
    getters: {
        
    },
    mutations: {
    },
}